### ISSUE TITLE
🐛 url 요청에 '/'가 안 들어갈 경우 에러 발생

### ISSUE THREAD

**Issue by jeongyunnim** [bitbit-Merry-go-round/Transcendence-BE#21]
## 🔎 어떤 버그인가요?
> url 요청에 '/'가 안 들어갈 경우 에러 발생
> GET 요청은 문제가 없음.

## 📝 어떤 상황에서 발생한 버그인가요?
- given
    - edit 페이지에서 이미지와 상태 메시지 변경.
    - `fetch(`http://${window.location.hostname}:8000/users/${user}/profile`)`
- when
    - edit 페이지에서 버튼 클릭
<img width="1176" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/8a1148b7-e9bc-48b9-b279-d2986eee582f">

- then
    - 프로필이 변경되어야 한다.

## 🧪 예상 결과
> 프로필의 변경

## ✅ To-do
- [ ] 서버 설정 변경

**Comment by hyemch** [comment]
APPEND_SLASH 설정을 하게 되면 장고는 끝에 슬래시가 없는 버전을 슬래시가 있는 버전으로 자동으로 리디렉션 하게 되는데, 이때 리디렉션은 request의 상태를 함께 전달하지 않기 때문에 데이터가 손실된다고 합니다.
url 요청을 슬래시가 있는 버전으로 보내주시면 될 것 같습니다😊! 
[docs django](https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-APPEND_SLASH)
