### ISSUE TITLE
🐛 DB root에 대한 오류

### ISSUE THREAD

**Issue by ohhamma** [bitbit-Merry-go-round/Transcendence-BE#27]
## 🔎 어떤 버그인가요?
- db 컨테이너 실행 시 아래의 오류메시지가 계속 뜸
- 근데 실제 컨테이너 실행에는 영향을 주지 않음

## 📝 어떤 상황에서 발생한 버그인가요?
<img width="699" alt="스크린샷 2024-03-28 19 48 09" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/81293930/1479e31c-f2ee-4ff3-a736-74852da6819c">

## 🧪 예상 결과
- 에러가 안 뜨게 만들어봅시다

## ✅ To-do
- [x] 원인 분석
- [x] 해결 

## 📚 참고할만한 자료
> 선택사항입니다

**Comment by Seotephen** [comment]
## health check

<img width="516" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/adb8759c-7c50-46dd-b20d-cc74f2b520f1">

<img width="622" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/7908161a-601f-49a8-8c03-e2ba6a1dfe01">

> 해당 인터벌 간격으로 발생 되길래 health check 부분을 주석처리해보았더니 FATAL에러가 뜨지 않습니다.
@ohhamma

**Comment by hyemch** [comment]
<img width="436" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/102580205/ed28382a-9b15-4153-bed0-2702fe935131">

환경 변수 `PGUSER` `PGDATABASE`와 같은 형식으로 써주어야 합니다! 
https://www.postgresql.org/docs/14/libpq-envars.html
위 링크를 참조해보시면, `POSTGRES...`와 같은 형식의 환경변수가 없습니다. 
그래서 `healthcheck`의 `test` 문이 참조하는 환경변수가 `PG..`인 것 같습니다.

수정 부탁드립니다! @jeongyunnim @ohhamma
