### ISSUE TITLE
✨ django proxy 기능 요청

### ISSUE THREAD

**Issue by jeongyunnim** [bitbit-Merry-go-round/Transcendence-BE#37]
## 📝 어떤 기능인가요?
> OAuth 시 Cors 에러를 해결하기 위해 필요해요..
다른 방법이 있다면, 그리고 그 방법이 쉽다면,, 그렇게 해주세요

## ✅ 작업 상세 내용
- [ ] 프록시 기능을 추가

## 📚 참고할만한 자료
`path('proxy/', proxy_view, name='proxy_view')`를 추가하여 아래와 같이 연결을 시도했는데 token이 유효하지 않아 거부 당하네요..

<img width="805" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/04e0969e-5c27-4a15-9b4b-68c7c8c131ca">

**Comment by Seotephen** [comment]
OAuth workflow 중 문제 부분 -> 3번 과정

<img width="1153" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/49594070-4654-4c0e-9d77-10e9e2639348">

**Comment by ohhamma** [comment]
proxy server 없이 해결했습니다 !
