### ISSUE TITLE
🐛 User DB에 대한 오류

### ISSUE THREAD

**Issue by jeongyunnim** [bitbit-Merry-go-round/Transcendence-BE#38]
## 🔎 어떤 버그인가요?
> login 이후 DB에 접근하면 ORM에러가 발생해요.

## 📝 어떤 상황에서 발생한 버그인가요?
> 42를 통해 원격 로그인 완료 > users/42/callback 으로 접근하면 `users/views.py`의 `fourtytwo_callback()`에서 오류가 발생해요.

## 🧪 예상 결과
> 로그인 결과 확인..

## ✅ To-do
- [ ] 원인 분석
- [ ] 문제 해결

## 📚 참고할만한 자료

에러 페이지

<img width="902" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/94da1d4f-60cd-4b19-aab9-90367ef98d3f">
에러가 발생한 부분
<img width="886" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/d5cee802-9518-4c3e-904d-c6b0bd3da65c">

위 지역 변수 값의 추가 정보

```
request	<WSGIRequest: GET '/users/42/callback/?code=b07accab8105e5520153535f4c817400282a78b32ac65117d448f4b43b054898'>
token_response	<Response [200]>
token_response_json	 
    {'access_token': 'e140832e7f2e1c0380d24442569de1e675c9446ed24adfdca46b5cc0d9297ea2',
     'created_at': 1711882331,
     'expires_in': 4308,
     'refresh_token': '0cca785140bafb71bdd6f15a10c5e91f64fd49d5a983127ecdacee230f714a52',
     'scope': 'public',
     'secret_valid_until': 1713851332,
     'token_type': 'bearer'}
username	'jeseo'
```

문제의 모델 User

<img width="732" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/da0c086f-1c98-48ca-b284-39ab298fcd38">

User이 상속하는 AbstractBaseUser

<img width="591" alt="image" src="https://github.com/bitbit-Merry-go-round/Transcendence-BE/assets/99523863/ceafb833-9c06-40a5-ba2b-5b5288568632">

> 의아한 점
> 왜 기본으로 생성되는 필드가 생성되지 않은 채로 있을까요?

**Comment by Seotephen** [comment]
https://github.com/bitbit-Merry-go-round/Transcendence-BE/blame/609c17616ea0023dda6660c16108bd5b4d314738/srcs/backend/srcs/users/adapter.py#L11

세미콜론 빼주세요~
(문제랑은 상관 없음)

**Comment by Seotephen** [comment]
로컬에 남아있던 데이터가 잘못 적용되어 생긴 문제 였습니다.
