### ISSUE TITLE
✨ 자신을 검색했을 때 자신을 나타내는 boolean이 필요해요

### ISSUE THREAD

**Issue by jeongyunnim** [bitbit-Merry-go-round/Transcendence-BE#48]
## 📝 어떤 기능인가요?
> 자신을 검색한다면, 혹은 다른 유저의 전적을 통해 자신의 정보를 불러왔을 때, is_friend 항목을 보고 친구 추가 혹은 삭제 버튼이 노출될 수 있습니다.

## ✅ 작업 상세 내용
- [x] is_me(가명) field 추가

**Comment by ohhamma** [comment]
필요 없을 것 같아 뺐었는데.. 다시 추가해야겠군요 !
