### ISSUE TITLE
♻️ 로컬 플레이에 맞게 리팩토링 필요

### ISSUE THREAD

**Issue by jeongyunnim** [bitbit-Merry-go-round/Transcendence-BE#55]
## 📝 어떤 기능인가요?
- 로컬 플레이에 맞게 리팩토링

## ✅ 작업 상세 내용
- [ ] 모드 뷰 변경
- [ ] 매칭 뷰 변경
- [ ] 안내 메시지 추가

**Comment by Seotephen** [comment]
FE 이슈를 잘못 올렸습니다.
